apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-postgress
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:12
          ports:
            - containerPort: 8000

---
apiVersion: v1
kind: Service
metadata:
  name: db-postgress
spec:
  selector:
    app: postgres
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
